server:
  port: 1001
#management:
#  port: 10001
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomage?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: rootoo
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.yss.domain